apiVersion: v2
publisher: redhat
name: ansible
version: latest
type: VS Code extension
displayName: Ansible
title: Ansible
description: Ansible language support
icon: /images/redhat-ansible-icon.png
category: Programming Languages
repository: https://github.com/ansible/vscode-ansible.git
spec:
  containers:
    - image: registry.redhat.io/devspaces/udi-rhel8@sha256:d55549aad15742f6f7310da0c7abc1e65dd5d3ad2e3efb8fbf414cf91b9efac7
      name: vscode-ansible
      memoryLimit: 256Mi
      memoryRequest: 20Mi
      cpuRequest: 30m
      cpuLimit: 500m
  extensions:
    - relative:extension/resources/open-vsx_org/api/redhat/ansible/0.14.73/file/redhat.ansible-0.14.73.vsix
